spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: ${bootstrap-servers:localhost:9093}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-event-listener-group
      ssl:
        trust-store-location: file:/certs/client.truststore.jks
        trust-store-password: ${trust_store_password:123456789}
        key-store-location: file:/certs/server.keystore.jks
        key-store-password: ${key_store_password:123456789}
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
    producer:
      bootstrap-servers: ${bootstrap-servers:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/certs/client.truststore.jks
        trust-store-password: ${trust_store_password:123456789}
        key-store-location: file:/certs/server.keystore.jks
        key-store-password: ${key_store_password:123456789}
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    data-username: sa
    data-password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
---
spring:
  profiles: test
  kafka:
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        -   localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
