spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      retries: 10
      retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093
        acks: all
---