spring:
  profiles:
    active: local
---
spring:
  profiles: local
  data:
    mongodb:
        uri: mongodb://producer:1234@mongo:27017/producer-db
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: ${bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/certs/client.truststore.jks
        trust-store-password: ${trust_store_password:123456789}
        key-store-location: file:/certs/server.keystore.jks
        key-store-password: ${key_store_password:123456789}
      properties:
        retries: 10
        retry.backoff.ms: 1000
        transaction.timeout.ms: 10000
        acks: all
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

---

spring:
  profiles: test
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093

---